Revert "[hip-tests] Replace HIP_SKIP_THIS_TEST with Catch2  SKIP macro" (#5923)
Reverts ROCm/rocm-systems#4505

See https://github.com/ROCm/rocm-systems/issues/5915, this raced with
https://github.com/ROCm/rocm-systems/pull/5575 and broke the build:
```
2026-05-08T13:02:48.3238393Z [hip-tests] /__w/TheRock/TheRock/rocm-systems/projects/hip-tests/catch/unit/event/Unit_hipEventIpc_shm_cleanup.cc:64:16: error: expected identifier
2026-05-08T13:02:48.3242073Z [hip-tests]    64 |       HipTest::HIP_SKIP_TEST("Device uses native IPC signals; /dev/shm cleanup not applicable");
2026-05-08T13:02:48.3242172Z [hip-tests]       |                ^
2026-05-08T13:02:48.3242752Z [hip-tests] /__w/TheRock/TheRock/rocm-systems/projects/hip-tests/catch/unit/event/Unit_hipEventIpc_shm_cleanup.cc:64:7: error: unexpected namespace name 'HipTest': expected expression
2026-05-08T13:02:48.3243063Z [hip-tests]    64 |       HipTest::HIP_SKIP_TEST("Device uses native IPC signals; /dev/shm cleanup not applicable");
2026-05-08T13:02:48.3243134Z [hip-tests]       |       ^
2026-05-08T13:02:48.3243616Z [hip-tests] /__w/TheRock/TheRock/rocm-systems/projects/hip-tests/catch/unit/event/Unit_hipEventIpc_shm_cleanup.cc:64:14: error: expected ';' after expression
2026-05-08T13:02:48.3243923Z [hip-tests]    64 |       HipTest::HIP_SKIP_TEST("Device uses native IPC signals; /dev/shm cleanup not applicable");
2026-05-08T13:02:48.3243996Z [hip-tests]       |              ^
2026-05-08T13:02:48.3244061Z [hip-tests]       |              ;
2026-05-08T13:02:48.3244417Z [hip-tests] 3 errors generated when compiling for gfx1010.
```
[rocm-systems] ROCm/rocm-systems#5923 (commit 5b20c93)